steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
          python-version: '2.x' # Version range or exact version of a Python version to use, using semvers version range syntax.
          architecture: 'x64' # (x64 or x86)
    - run: python my_script.py

jobs:
    build:
        runs-on: ubuntu-16.04
        strategy:
            matrix:
                python: [ '2.x',  ]
        name: Python ${{ matrix.python }} sample
        steps:
            - uses: actions/checkout@master
            - name: Setup python
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python }}
                  architecture: x64
            - run: python my_script.py
